set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.tmux/plugins/'

set -g default-terminal "screen-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

set -g @catppuccin_flavour 'mocha'
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_status_background "default"

run '~/.tmux/plugins/tpm/tpm'
run '~/.tmux/plugins/catppuccin/catppuccin.tmux'
set -g prefix C-a
unbind C-b
bind C-a send-prefix

set -g prefix C-a
unbind C-b
bind C-a send-prefix

bind - split-window -v -c "#{pane_current_path}"
bind = split-window -h -c "#{pane_current_path}"
bind w choose-window
bind X kill-window
setw -g mode-keys vi
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "pbcopy"
